spring:
  datasource:
    url: jdbc:postgresql://dpg-d5vev7npm1nc73chk5t0-a:5432/webtrack_db
    username: webtrack_db_user
    password: QaJyrKxha0c1DhS5RlxM6rrCI6dJvSho
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
