package com.webtrak.util;

import io.jsonwebtoken.*;
import io.jsonwebtoken.security.Keys;

import java.security.Key;
import java.util.Date;

public class JwtUtil {

    // ✅ Secure key generated by library
    private static final Key key =
            Keys.secretKeyFor(SignatureAlgorithm.HS256);

    private static final long EXPIRY =
            1000 * 60 * 60 * 24; // 1 day

    public static String generate(String userId, String email, String role) {

        return Jwts.builder()
                .setSubject(userId)
                .claim("email", email)
                .claim("role", role)
                .setIssuedAt(new Date())
                .setExpiration(
                        new Date(System.currentTimeMillis() + EXPIRY)
                )
                .signWith(key)
                .compact();
    }
}
